"""add sheet sync columns to content_rows

Revision ID: 7c37cb595e50
Revises: 2c1fc48e4ea9
Create Date: 2026-03-17 16:23:15.188365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c37cb595e50'
down_revision: Union[str, Sequence[str], None] = '2c1fc48e4ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_row_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sheet_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_rows', schema=None) as batch_op:
        batch_op.drop_column('sheet_synced_at')
        batch_op.drop_column('sheet_row_number')

    # ### end Alembic commands ###
